FROM caddy@sha256:5f5c8640aae01df9654968d946d8f1a56c497f1dd5c5cda4cf95ab7c14d58648

USER root
RUN cp /usr/bin/caddy /usr/bin/caddy.nocap \
    && chmod 0755 /usr/bin/caddy.nocap \
    && mv /usr/bin/caddy.nocap /usr/bin/caddy

USER 65532:65532
